In [22]:
using LinearAlgebra

In [23]:
function hat(v)
    return [0 -v[3] v[2];
            v[3] 0 -v[1];
            -v[2] v[1] 0]
end
function unhat(S)
    return 0.5*[S[3,2]-S[2,3];
                S[1,3]-S[3,1];
                S[2,3]-S[3,2]]
end

unhat (generic function with 1 method)

In [24]:
#Make a random attitude
Qtrue = exp(hat(randn(3)))

3×3 Matrix{Float64}:
  0.714097  0.686494  -0.137079
 -0.640789  0.56215   -0.522854
 -0.281877  0.461208   0.841328

In [25]:
#Make some random vectors
n = 10
r_B = randn(3,n)
for k = 1:n
    r_B[:,k] .= r_B[:,k]/norm(r_B[:,k])
end

r_N = Qtrue*r_B

3×10 Matrix{Float64}:
 -0.565076  0.839081   0.519197    …   0.0691212  -0.802324   0.491241
 -0.72535   0.301035  -0.85465        -0.907583    0.207862  -0.736219
  0.393136  0.453123  -0.00275012     -0.414144   -0.559526   0.465472

In [33]:
#Add some noise
for k = 1:n
    r_B[:,k] += 0.1*randn(3)
    r_B[:,k] .= r_B[:,k]/norm(r_B[:,k])
end

In [34]:
#Attitude Profile Matrix
w = ones(n)
B = zeros(3,3)
for k = 1:n
    B += w[k]*r_B[:,k]*r_N[:,k]'
end

In [35]:
F = svd(B)

SVD{Float64, Float64, Matrix{Float64}, Vector{Float64}}
U factor:
3×3 Matrix{Float64}:
  0.236296   0.85694   -0.458058
 -0.969482   0.176226  -0.170437
 -0.0653324  0.484353   0.87243
singular values:
3-element Vector{Float64}:
 4.029641251074404
 3.8527774617481607
 2.0435471683499533
Vt factor:
3×3 Matrix{Float64}:
 -0.495036  -0.65803   -0.567394
  0.705464  -0.685605   0.179626
 -0.507208  -0.311355   0.803616

In [36]:
Q1 = F.V*F.U'

3×3 Matrix{Float64}:
  0.719896  0.690696  -0.0684674
 -0.600394  0.570193  -0.56072
 -0.348247  0.444768   0.82517

In [37]:
#Is the solution orthogonal?
Q1'*Q1

3×3 Matrix{Float64}:
  1.0          -1.38778e-16  0.0
 -1.38778e-16   1.0          2.77556e-16
  0.0           2.77556e-16  1.0

In [38]:
#Is it "special"?
det(Q1)

0.9999999999999999

In [39]:
#Does it match the true solution?
Q1'*Qtrue

3×3 Matrix{Float64}:
 0.996965    -0.00392134  -0.0777546
 0.00248093   0.999824    -0.0186131
 0.0778139    0.0183637    0.996799

In [40]:
#Error in degrees
(180/pi)*norm(unhat(log(Q1'*Qtrue)))

4.706786977658144